# Generated by Django 4.1.5 on 2023-01-19 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_officer_agency'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
            ],
        ),
        migrations.AddField(
            model_name='officer',
            name='rol',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.rolprofile', verbose_name='Rol'),
            preserve_default=False,
        ),
    ]
