# Generated by Django 4.1.5 on 2023-01-20 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rolprofile_officer_rol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'ordering': ['-name'], 'verbose_name': 'Agency', 'verbose_name_plural': 'Agencies'},
        ),
        migrations.AlterModelOptions(
            name='citation',
            options={'ordering': ['-issued_date'], 'verbose_name': 'Citation', 'verbose_name_plural': 'Citations'},
        ),
        migrations.AlterModelOptions(
            name='officer',
            options={'ordering': ['-user'], 'verbose_name': 'officer', 'verbose_name_plural': 'Officers'},
        ),
        migrations.RemoveField(
            model_name='officer',
            name='rol',
        ),
        migrations.DeleteModel(
            name='RolProfile',
        ),
    ]
