# Generated by Django 4.1.5 on 2023-01-19 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('location', models.TextField(verbose_name='Location')),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.agency', verbose_name='Agency')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('no_citation', models.CharField(max_length=255, verbose_name='No. Citation')),
                ('violation_date', models.DateField(verbose_name='Violation Date')),
                ('vilation_time', models.TimeField(verbose_name='Violation Time')),
                ('route', models.CharField(max_length=255, verbose_name='Route')),
                ('county', models.CharField(max_length=255, verbose_name='County')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('vehicle_type_passenger', models.CharField(max_length=100, verbose_name='Vehicle Type Passenger')),
                ('oln_state_passenger', models.CharField(max_length=100, verbose_name='OLN State Passenger')),
                ('oln_passenger', models.CharField(max_length=100, verbose_name='OLN Passenger')),
                ('class_oln_passenger', models.CharField(max_length=100, verbose_name='Class OLN Passenger')),
                ('cdl_passenger', models.CharField(max_length=100, verbose_name='CDL Passenger')),
                ('name_passenger', models.CharField(max_length=100, verbose_name='Name Passenger')),
                ('gender_passenger', models.CharField(max_length=100, verbose_name='Gender Passenger')),
                ('hair_passenger', models.CharField(max_length=100, verbose_name='Hair Passenger')),
                ('eyes_passenger', models.CharField(max_length=100, verbose_name='Eyes Passenger')),
                ('height_passenger', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Height Passenger')),
                ('address_passenger', models.TextField(verbose_name='Address Passenger')),
                ('city_passenger', models.CharField(max_length=150, verbose_name='City Passenger')),
                ('state_passenger', models.CharField(max_length=150, verbose_name='State Passenger')),
                ('phone_passenger', models.CharField(max_length=150, verbose_name='Phone Passenger')),
                ('email_passenger', models.EmailField(max_length=254, verbose_name='Email Passenger')),
                ('vin_car', models.CharField(max_length=255, verbose_name='Vin Car')),
                ('color_car', models.CharField(max_length=255, verbose_name='Color Car')),
                ('year_car', models.CharField(max_length=255, verbose_name='Year Car')),
                ('make_car', models.CharField(max_length=255, verbose_name='Make Car')),
                ('model_car', models.CharField(max_length=255, verbose_name='Model Car')),
                ('crash', models.CharField(max_length=255, verbose_name='Crash')),
                ('passenger', models.BooleanField(verbose_name='Passenger')),
                ('spanish_speaker', models.CharField(max_length=255, verbose_name='Spanish Speaker')),
                ('in_car_video', models.BooleanField(verbose_name='In Car Video')),
                ('body_camera', models.BooleanField(verbose_name='Body Camera')),
                ('school_zone', models.BooleanField(verbose_name='School Zone')),
                ('cosntruction_zone', models.BooleanField(verbose_name='Cosntruction Zone')),
                ('workers_present', models.BooleanField(verbose_name='Workers Present')),
                ('issued_date', models.DateField(verbose_name='Issued Date')),
                ('badge', models.CharField(max_length=100, verbose_name='Iadge')),
                ('issued_time', models.TimeField(verbose_name='Issued Time')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.officer', verbose_name='Issued by')),
            ],
        ),
    ]
