# Generated by Django 4.1.5 on 2023-01-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_agency_options_alter_citation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='badge',
            field=models.CharField(max_length=100, verbose_name='Badge'),
        ),
        migrations.AlterField(
            model_name='citation',
            name='crash',
            field=models.BooleanField(verbose_name='Crash'),
        ),
        migrations.AlterField(
            model_name='citation',
            name='spanish_speaker',
            field=models.BooleanField(verbose_name='Spanish Speaker'),
        ),
    ]
